### ISSUE TITLE
Don't use String.raw for the css tag

### ISSUE THREAD

**Issue by jaydenseric** [ChrisAckerman/react-css-in-js#1]
Was just passing by and noticed this:

https://github.com/ChrisAckerman/react-css-in-js/blob/c887d03b486e42ce38c6a3f63d31e75b7e3c5684/src/css.ts#L1-L4

Here is an explanation why not to use `String.raw`:

https://github.com/jaydenseric/fake-tag#why-not-stringraw

[`fake-tag`](https://npm.im/fake-tag) can be used to get around the edge cases:

```js
/**
 * Tagged template function for CSS-like styles.
 */
export { default as css } from 'fake-tag';
```

**Comment by ChrisAckerman** [comment]
That is very interesting. I assumed that's what String.raw was, but apparently it's "special". Thanks for that!

**Comment by ChrisAckerman** [comment]
Hmm... so, I think I'm going to leave it as.

I hadn't thought of the literal back-tick case, but I do want back-slashes to be literal, rather than having to escape them. I want the CSS text to be as cut-and-paste compatible as possible. For example, If you're copying a [S]CSS snippet from the web which contains unicode escape sequences, I don't want you to have to go through and double all the backslashes. I think finding a literal back-tick in a style string would be the rarer case.

If you _need_ a literal back-tick, you can do it with ``${"`"}``. But it turns out CSS just ignores the extra back-slash if it's followed by a character that doesn't need escaping, like a back-tick. So ``&:after { content: "\`" }`` actually works just fine, and prints a single back-tick.
